name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-08"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTIxYzVmZTktZjZhOC00ZjA5LTliNjMtNWNkYTRkNTYyZjJmIiwidGVuYW50X2lkIjoiODVhZGVjNDlkYTExNTNiMDRlODgwOGFkNTA5YTQ2NmI3ZjY5ZWZkMTA4MDIyZjk3NGRmZWY5MWE5Y2Y1MTc2ZCIsImludGVybmFsX3NlY3JldCI6ImY2OGIwNTE4LWVmYTgtNDUxMi04MDcxLWE5YTkxYTc5M2I3NiJ9.vHRhRmEm-cqcKOke523gprCCK8UwlzpkSwoAfPiVDJU"
